{% set name = "arq" %}
{% set version = "0.27.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/arq-{{ version }}.tar.gz
  sha256: 302a16e78396923fbff0f542fee0e04c731cc549195d18d039be3cc1a3431106

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - arq = arq.cli:cli

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
  run:
    - python >={{ python_min }}
    - redis-py >=4.2.0,<6

    # (extras_require for reddis[hiredis])
    - hiredis >=1.0.0

    - click >=8.0

test:
  imports:
    - arq
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/samuelcolvin/arq
  summary: Job queues in python with asyncio and redis
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
