{% set name = "arq" %}
{% set version = "0.23" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/arq-{{ version }}.tar.gz
  sha256: a1187c550bf35e524cf95353b1e64c60e48d826aad448f85ede7472b1bb6ac37

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - arq = arq.cli:cli

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - aioredis >=1.1.0
    - click >=6.7
    - pydantic >=1
    - dataclasses >=0.6
    - typing-extensions >=3.7

test:
  imports:
    - arq
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/samuelcolvin/arq
  summary: Job queues in python with asyncio and redis
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
