{% set name = "arq" %}
{% set version = "0.25.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/arq-{{ version }}.tar.gz
  sha256: d176ebadfba920c039dc578814d19b7814d67fa15f82fdccccaedb4330d65dae

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - arq = arq.cli:cli

requirements:
  host:
    - pip
    - python >=3.7
    - hatchling
  run:
    - python >=3.7
    - redis-py >=4.2.0

    # (extras_require for reddis[hiredis])
    - hiredis >=1.0.0

    - click >=8.0
    - typing-extensions >=4.1.0

test:
  imports:
    - arq
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/samuelcolvin/arq
  summary: Job queues in python with asyncio and redis
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
